### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by tycode** [slhck/audio-normalize#1]
1) Please convert all line endings to UNIX format (they are currently in DOS format), otherwise the shebang doesn't work.

2) Line 135: `target_level = args.level` should be `target_level = float(args.level)`. Otherwise, Python 2.7 complains that it cannot subtract a float from a string on the next line.

3) Please add an option (e.g. --max) to normalize maximum volume instead of mean volume, which would effectively change line 136 from `target_level - mean` to `target_level - maximum`. (This is how Audacity normalizes.)

4) Warning on line 74 in ffmpeg_adjust_volume should call print, not print_verbose; I shouldn't have to use -v to see this warning.

**Comment by slhck** [comment]
Thanks for bringing these up.
