### ISSUE TITLE
Don't know what is going on here.

### ISSUE THREAD

**Issue by michaelcrossland** [slhck/audio-normalize#13]
![capture](https://cloud.githubusercontent.com/assets/1592324/12688551/911bc598-c69c-11e5-8b33-071001c2d9a7.PNG)
I just downloaded and installed Python 3.5.1 from the site and got that installed. I got your script using the pip you had listed on the site. That all worked.
Then I tried a test dry run on a wav file I have it less then 30 seconds all told. Here is what I got when I run your script.

`C:\Users\micha\Documents\Script sounds>ffmpeg-normalize -n -d -v done.wav
2016-01-29 15:13:03,564 - ffmpeg_normalize - DEBUG - {'--debug': True,
 '--dry-run': True,
 '--force': False,
 '--level': '-26',
 '--max': False,
 '--prefix': 'normalized',
 '--verbose': True,
 '-m/--max': None,
 '<input-file>': ['done.wav']}
2016-01-29 15:13:03,565 - ffmpeg_normalize - INFO - reading file done.wav
2016-01-29 15:13:03,565 - ffmpeg_normalize - DEBUG - [command] c:\ffmpeg\bin\ffmpeg -i "done.wav" -filter:a "volumedetect" -vn -sn -f null /dev/null
2016-01-29 15:13:03,655 - ffmpeg_normalize - DEBUG - b"ffmpeg version N-74566-g531b0a3 Copyright (c) 2000-2015 the FFmpeg developers\r\n  built with gcc 4.9.3 (GCC)\r\n  conf
iguration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-li
bass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enabl
e-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-l
ibspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enab
le-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib\r\n  libavutil      54. 31.100 / 54. 31.100\r\n
libavcodec     56. 58.100 / 56. 58.100\r\n  libavformat    56. 40.101 / 56. 40.101\r\n  libavdevice    56.  4.100 / 56.  4.100\r\n  libavfilter     5. 36.100 /  5. 36.100\r\n
  libswscale      3.  1.101 /  3.  1.101\r\n  libswresample   1.  2.101 /  1.  2.101\r\n  libpostproc    53.  3.100 / 53.  3.100\r\nGuessed Channel Layout for  Input Stream #
0.0 : stereo\r\nInput #0, wav, from 'done.wav':\r\n  Metadata:\r\n    encoder         : Lavf56.40.101\r\n  Duration: 00:00:08.24, bitrate: 705 kb/s\r\n    Stream #0:0: Audio:
 pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, 2 channels, s16, 705 kb/s\r\nOutput #0, null, to '/dev/null':\r\n  Metadata:\r\n    encoder         : Lavf56.40.101\r\n    Strea
m #0:0: Audio: pcm_s16le, 22050 Hz, stereo, s16, 705 kb/s\r\n    Metadata:\r\n      encoder         : Lavc56.58.100 pcm_s16le\r\nStream mapping:\r\n  Stream #0:0 -> #0:0 (pcm
_s16le (native) -> pcm_s16le (native))\r\nPress [q] to stop, [?] for help\r\nsize=N/A time=00:00:08.23 bitrate=N/A    \r\nvideo:0kB audio:710kB subtitle:0kB other streams:0kB
 global headers:0kB muxing overhead: unknown\r\n[Parsed_volumedetect_0 @ 00000000052411c0] n_samples: 363268\r\n[Parsed_volumedetect_0 @ 00000000052411c0] mean_volume: -20.3
dB\r\n[Parsed_volumedetect_0 @ 00000000052411c0] max_volume: -4.9 dB\r\n[Parsed_volumedetect_0 @ 00000000052411c0] histogram_4db: 2\r\n[Parsed_volumedetect_0 @ 00000000052411
c0] histogram_5db: 30\r\n[Parsed_volumedetect_0 @ 00000000052411c0] histogram_6db: 212\r\n[Parsed_volumedetect_0 @ 00000000052411c0] histogram_7db: 472\r\n"
Traceback (most recent call last):
  File "C:\Python35-32\Scripts\ffmpeg-normalize-script.py", line 9, in <module>
    load_entry_point('ffmpeg-normalize==0.1.3', 'console_scripts', 'ffmpeg-normalize')()
  File "c:\python35-32\lib\site-packages\ffmpeg_normalize\__main__.py", line 197, in main
    mean, maximum = ffmpeg_get_mean(input_file)
  File "c:\python35-32\lib\site-packages\ffmpeg_normalize\__main__.py", line 143, in ffmpeg_get_mean
    mean_volume_matches = re.findall(r"mean_volume: ([\-\d\.]+) dB", output)
  File "c:\python35-32\lib\re.py", line 213, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object`

Now I'm new to python but not new to programming, but this debug dump did not help me to try to find what was causing this. Before you ask I'm run windows 10 build 11099.rs1_release.160109-1156 it is a 64 bit build and I have 8GB of RAM. So I hope this helps you in trying to fix the script. I would love to use it as it's something I have need very badly for some time now.
I have added a screen grab of my terminal out put.

**Comment by benjaoming** [comment]
I don't think this project has python 3 support, try python 2

**Comment by michaelcrossland** [comment]
@benjaoming thanks that worked. I sew on the front page readme that it said 2 or 3. Will live and learn.

**Comment by benjaoming** [comment]
That seems like something that should be fixed one way or the other :)
