### ISSUE TITLE
Not a Issue per say.

### ISSUE THREAD

**Issue by michaelcrossland** [slhck/audio-normalize#14]
I'm new to the whole Python programming game, but where in the code is the -28 or 26 dB hard coded into the code? I can't find it and been over all of the files on here. I would like to know where that is set because I would like to mod it so i can have it ask for a level and remember that and not have to use a over ride eatch I make a call to the program in my batch files.

**Comment by slhck** [comment]
There's a bit of trickery involved here… well, it uses [docopt](https://pypi.python.org/pypi/docopt) to automatically get the options from the documentation part at the top of the script.

You can change the script to simply use another variable for the level instead of this:

```python
target_level = float(args['--level'])
```
