### ISSUE TITLE
How a bug with the newest code.

### ISSUE THREAD

**Issue by michaelcrossland** [slhck/audio-normalize#16]
Don't know what is going on but this is what I keep getting when I run the script with the "-v" flage.
Traceback (most recent call last):
  File "C:\Python27\Scripts\ffmpeg-normalize-script.py", line 9, in <module>
    load_entry_point('ffmpeg-normalize==0.2.2', 'console_scripts', 'ffmpeg-normalize')()
  File "c:\python27\lib\site-packages\ffmpeg_normalize\__main__.py", line 247, in main
    target_level = float(args['--level'])
ValueError: could not convert string to float: -v

**Comment by auricgoldfinger** [comment]
I guess you ran the command with "-l -v"?
You have to provide a number directly after the -l

If not, can you post your full command that your trying to execute?

**Comment by michaelcrossland** [comment]
I got to work after I uninstalled it  though pip and then cleared the cache
and reinstalled.  Look like it to do with in what order I was calling the
flags and some mods I had to the old installed script.

**Comment by auricgoldfinger** [comment]
The order is indeed important, as some parameters require extra information. -l -v would be invalid but -l -26 -v should work perfectly.

Glad it's solved.
