### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by winterflags** [slhck/audio-normalize#7]
When trying `sudo pip install ffmpeg-normalize` on OS X with Python 2.7, I get this error message:

```bash
Collecting ffmpeg-normalize
  Downloading ffmpeg-normalize-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-ab9SEV/ffmpeg-normalize/setup.py", line 9, in <module>
        with open('HISTORY.rst') as history_file:
    IOError: [Errno 2] No such file or directory: 'HISTORY.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-ab9SEV/ffmpeg-normalize
```

I haven't had this problem before when installing libraries so I'm not sure what to make of it.

**Comment by slhck** [comment]
I'm not a big expert on pip and PyPI. 

@benjaoming / @mvbattista, do you know why the history file is missing? Do we need to update the PyPI tarfile?

**Comment by mvbattista** [comment]
@slhck I'm not the one that controls the build that goes out to PyPI. I just made my fix to that it could install after the name change.

**Comment by slhck** [comment]
@mvbattista Yes, sorry, I thought you also were more knowledgeable than me on that :) Sorry for the ping in case you were not interested anymore.
